version: 2

models:
  - name: silver_timeseries
    description: "Normalized OSRS timeseries data with canonical column names"
    columns:
      - name: item_id
        description: "OSRS item identifier"
        tests:
          - not_null
      - name: ts
        description: "Timestamp in UTC"
        tests:
          - not_null
      - name: price_high
        description: "High price for the period"
        tests:
          - non_negative
      - name: price_low
        description: "Low price for the period"
        tests:
          - non_negative
      - name: price_avg_high
        description: "Average high price for the period"
        tests:
          - non_negative
      - name: price_avg_low
        description: "Average low price for the period"
        tests:
          - non_negative
      - name: volume
        description: "Trading volume"
        tests:
          - non_negative
      - name: source
        description: "Data source identifier"
        tests:
          - not_null
          - accepted_values:
              values: ['osrs_wiki_api']
      - name: load_ts
        description: "Timestamp when data was loaded"
        tests:
          - not_null
    tests:
      - unique:
          column_name: "item_id || '|' || ts"
          name: unique_item_ts_combination
